export default {
  height:'auto',
  calcHeight: 30,
  tip: false,
  searchShow: true,
  searchMenuSpan: 6,
  border: true,
  index: true,
  viewBtn: true,
  selection: true,
  menuWidth: 300,
  column: [
    {
      label: "用户订单ID",
      prop: "id",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "用户ID",
      prop: "userId",
      type: "input",
      dicUrl: "/blade-system/dict/dictionary?code=sex",
      dataType: "number",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "订单ID",
      prop: "orderId",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "用户",
      prop: "userName",
      type: "input",
      addDisplay: false,
      editDisplay: true,
      viewDisplay: true,
      search: true,
      disabled: true,
      labelWidth: 120,
    },
    {
      label: "商户",
      prop: "storeName",
      type: "input",
      addDisplay: false,
      editDisplay: true,
      viewDisplay: true,
      search: true,
      disabled: true,
      labelWidth: 120,
    },
    {
      label: "订单",
      prop: "orderName",
      type: "input",
      addDisplay: false,
      editDisplay: true,
      viewDisplay: true,
      search: true,
      disabled: true,
      labelWidth: 120,
    },
    {
      label: "订单总金额",
      prop: "totalAmount",
      type: "number",
      labelWidth: 120,
    },
    // 订单状态 1:待支付 2:已支付 3:已发货 4:已收货 5:已完成 6:已取消
    {
      label: "订单状态",
      prop: "orderStatus",
      type: "select",
      dicData: [
        { label: "待支付", value: 1 },
        { label: "已支付", value: 2 },
        { label: "已发货", value: 3 },
        { label: "已收货", value: 4 },
        { label: "已完成", value: 5 },
        { label: "已取消", value: 6 },
        { label: "库存不足", value: 7 },
        { label: "其他异常", value: 7 },
        { label: "已退款", value: 9 },
      ],
      search: true,
      labelWidth: 120,
    },
    // {
    //   label: "订单类型",
    //   prop: "orderType",
    //   type: "input",
    // },
    // {
    //   label: "订单来源",
    //   prop: "orderSource",
    //   type: "input",
    // },
    // {
    //   label: "优惠金额",
    //   prop: "discountAmount",
    //   type: "input",
    // },
    // {
    //   label: "实际支付金额",
    //   prop: "payAmount",
    //   type: "input",
    // },
    // {
    //   label: "支付时间",
    //   prop: "payTime",
    //   type: "input",
    // },
    {
      label: "创建时间",
      prop: "createTime",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
    },
    {
      label: "发货时间",
      prop: "deliveryTime",
      type: "datetime",
      labelWidth: 120,
    },
    {
      label: "收货时间",
      prop: "receiveTime",
      type: "datetime",
      labelWidth: 120,
    },
    {
      label: "订单完成时间",
      prop: "completeTime",
      type: "datetime",
      labelWidth: 120,
    },
    {
      label: "订单取消时间",
      prop: "cancelTime",
      type: "datetime",
      labelWidth: 120,
    },

    // {
    //   label: "支付方式ID",
    //   prop: "paymentMethodId",
    //   type: "input",
    // },
    {
      label: "创建人",
      prop: "createUser",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "创建部门",
      prop: "createDept",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "创建时间",
      prop: "createTime",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "修改人",
      prop: "updateUser",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "修改时间",
      prop: "updateTime",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "是否已删除",
      prop: "isDeleted",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "租户ID",
      prop: "tenantId",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
  ]
}
